language: python
python: "2.7"
sudo: required
dist: trusty
env:
  - ATTR=pip2nix.python27
  # TODO: pytest installation fails
  # - ATTR=pip2nix.python33
  - ATTR=pip2nix.python34
  - ATTR=pip2nix.python35
  - ATTR=pip2nix.python35
  - ATTR=docs
  - MODE=bootstrap
install: bash <(curl https://nixos.org/nix/install)
script:
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - if [ -z "$MODE" ]; then nix-build release.nix -A $ATTR; fi
  - if [ "$MODE" == "bootstrap" ]; then
      ./bootstrap.sh && git --no-pager diff;
    fi
