name: "build"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs: [nixpkgs-20.09, nixpkgs-20.03, nixpkgs-19.09, nixpkgs-19.03, nixpkgs-18.09]
        python: [python39, python38, python37, python36, python35, python27]
        exclude:
          - nixpkgs: nixpkgs-20.09
            python: python35
          - nixpkgs: nixpkgs-20.03
            python: python39
          - nixpkgs: nixpkgs-19.09
            python: python39
          - nixpkgs: nixpkgs-19.03
            python: python38
          - nixpkgs: nixpkgs-19.03
            python: python39
          - nixpkgs: nixpkgs-18.09
            python: python38
          - nixpkgs: nixpkgs-18.09
            python: python39
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build release.nix --argstr nixpkgs ${{ matrix.nixpkgs }} -A pip2nix.${{ matrix.python }}
  bootstrap:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        nixpkgs: [nixpkgs-20.09, nixpkgs-20.03, nixpkgs-19.09, nixpkgs-19.03, nixpkgs-18.09]
        python: [python39, python38, python37, python36, python35, python27]
        exclude:
          - nixpkgs: nixpkgs-20.03
            python: python39
          - nixpkgs: nixpkgs-19.09
            python: python39
          - nixpkgs: nixpkgs-19.03
            python: python39
          - nixpkgs: nixpkgs-19.03
            python: python38
          - nixpkgs: nixpkgs-18.09
            python: python39
          - nixpkgs: nixpkgs-18.09
            python: python38
          - python: python36
          - python: python35
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: NIXPKGS=${{ matrix.nixpkgs }} PYTHON=${{ matrix.python }} ./bootstrap.sh && git --no-pager diff
      - run: if [ "${{ matrix.nixpkgs }}" != "bootstrap" ]; then nix-build release.nix --argstr nixpkgs ${{ matrix.nixpkgs }} -A pip2nix.${{ matrix.python }}; fi
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs: [nixpkgs-20.09]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build release.nix --argstr nixpkgs ${{ matrix.nixpkgs }} -A docs
